window.PEAR_LANGUAGES = {
  "ru": {
    "name": "Русский",
    "strings": {
      "language": "Язык",
      "contrast": "Контраст",
      "title": "Калькулятор корней",
      "subtitle": "Числа, комплексные значения и выражения — в одном месте.",
      "inputTitle": "Что под корнем?",
      "expression": "Число или выражение",
      "hint": "Вводите только выражение под корнем. Например: 144 или sin(pi/2) + 3.",
      "mode": "Режим",
      "numeric": "Численный",
      "symbolic": "Аналитический",
      "angle": "Углы",
      "radians": "Радианы",
      "degrees": "Градусы",
      "digits": "Значащих цифр",
      "digitHint": "От 1 до 100",
      "both": "Показать оба корня уравнения z² = A",
      "calculate": "Вычислить корень ↗",
      "resultTitle": "Результат",
      "ready": "ГОТОВО К ВЫЧИСЛЕНИЮ",
      "principal": "Главный квадратный корень",
      "second": "Второй корень",
      "resultHint": "Введите выражение и нажмите «Вычислить корень».",
      "copy": "Скопировать результат",
      "examples": "Попробуйте на примере",
      "exampleHint": "Нажмите, чтобы вычислить",
      "exNumber": "Обычное число",
      "exComplex": "Комплексный корень",
      "exTrig": "Тригонометрия",
      "exFormula": "Формула с переменной",
      "syntax": "Проверьте скобки и знаки операций. Пример: sin(pi/2) + 3.",
      "syntaxText": "Операции: + − * / ^ и скобки. Функции: sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. Константы: pi (π), e, i. Дробная часть — через точку, например 3.5. Большое число: 2*10^50. Комплексное: 3+4*i. Названия функций вводите латиницей в нижнем регистре.",
      "symbolicHelp": "Численный режим вычисляет значения; аналитический — точные выражения. Имена переменных: латинская буква, затем буквы, цифры или _. Имена функций и pi, e, i зарезервированы. Формулы с переменными остаются под корнем: √(x²) нельзя всегда заменить на x. Аналитическая тригонометрия — только в радианах.",
      "accuracyHelp": "Точность — от 1 до 100 значащих цифр, а не знаков после запятой; незначащие нули в конце не дописываются. При вычитании близких больших чисел возможна потеря точности — повторите расчёт с большей точностью. Численный режим поддерживает радианы и градусы. Обратные тригонометрические функции принимают только вещественные аргументы в своей области определения. Длина ввода — до 1000 символов; время расчёта ограничено 8 секундами.",
      "footer": "pear · Калькулятор квадратных корней",
      "done": "ВЫЧИСЛЕНО",
      "busy": "Вычисляем…",
      "exact": "ТОЧНОЕ ВЫРАЖЕНИЕ",
      "formal": "ФОРМУЛА",
      "copied": "Скопировано",
      "fontDown": "Уменьшить шрифт",
      "fontUp": "Увеличить шрифт",
      "generic": "Не удалось вычислить выражение. Проверьте запись и область определения функций.",
      "input": "Введите выражение длиной до 1000 символов.",
      "division": "Деление на ноль невозможно.",
      "domain": "Аргумент вне области определения функции.",
      "variable": "В численном режиме замените переменные числами. Для переменных используйте аналитический режим и латинские имена.",
      "precision": "Выберите от 1 до 100 значащих цифр.",
      "function": "Такая функция не поддерживается. Откройте подсказку по вводу.",
      "arguments": "Функция должна иметь один аргумент.",
      "complexity": "Выражение слишком сложное. Разделите его на части.",
      "timeout": "Вычисление заняло больше 8 секунд. Упростите выражение.",
      "range": "Результат выходит за допустимый диапазон (показатель степени до 10 000).",
      "inverse": "Обратные тригонометрические функции здесь принимают только вещественные числа.",
      "symbolicDegrees": "В аналитическом режиме тригонометрические формулы вводятся в радианах.",
      "formalNote": "Формальный главный корень без упрощения. Значения переменных не заданы; область определения зависит от выражения.",
      "exactNote": "Точная символьная запись. Для десятичного значения выберите численный режим.",
      "valueLabel": "Подкоренное выражение: ",
      "precisionLabel": "Значащих цифр: ",
      "zeroNote": "У нуля один корень: 0.",
      "failed": "ОШИБКА ВВОДА",
      "stale": "НАСТРОЙКИ ИЗМЕНЕНЫ",
      "staleNote": "Нажмите «Вычислить корень», чтобы обновить результат.",
      "copyFailed": "Не удалось скопировать. Выделите результат вручную.",
      "syntaxTitle": "Как вводить выражения",
      "clear": "Очистить",
      "support": "Служба поддержки:",
      "power": "Возвести в степень",
      "powerTitle": "Возвести в степень",
      "powerDescription": "Введите число, переменную или выражение и нужную степень.",
      "powerBase": "Основание",
      "powerExponent": "Показатель степени",
      "basePlaceholder": "Например, x или 2 + 3",
      "exponentPlaceholder": "Например, 3 или 1/2",
      "cancel": "Отмена",
      "insertPower": "Вставить",
      "powerRequired": "Заполните основание и показатель степени.",
      "entryHelp": "Введите только то, что находится под квадратным корнем. Кнопка «Вычислить корень» извлечёт из этого выражения корень. Например, 144 → 12; −49 → 7i; 0 → 0. Enter — вычислить, Shift+Enter — новая строка. «Очистить» удаляет весь ввод и результат.",
      "powerHelp": "Кнопка с двумя квадратами вставляет произвольную степень: заполните основание и показатель. Можно предварительно выделить основание в строке ввода. Примеры: (x)^(3), (2+3)^(4), (16)^(1/2). Вручную используйте ^; умножение обозначайте *: 2*x. Для переменных выберите аналитический режим."
    }
  },
  "en": {
    "name": "English",
    "strings": {
      "language": "Language",
      "contrast": "Contrast",
      "title": "Root calculator",
      "subtitle": "Numbers, complex values and expressions in one place.",
      "inputTitle": "What is under the root?",
      "expression": "Number or expression",
      "hint": "Enter only the expression under the root. For example: 144 or sin(pi/2) + 3.",
      "mode": "Mode",
      "numeric": "Numeric",
      "symbolic": "Symbolic",
      "angle": "Angles",
      "radians": "Radians",
      "degrees": "Degrees",
      "digits": "Significant digits",
      "digitHint": "From 1 to 100",
      "both": "Show both roots of z² = A",
      "calculate": "Calculate root ↗",
      "resultTitle": "Result",
      "ready": "READY TO CALCULATE",
      "principal": "Principal square root",
      "second": "Second root",
      "resultHint": "Enter an expression and press Calculate root.",
      "copy": "Copy result",
      "examples": "Try an example",
      "exampleHint": "Click to calculate",
      "exNumber": "A simple number",
      "exComplex": "A complex root",
      "exTrig": "Trigonometry",
      "exFormula": "An expression with a variable",
      "syntaxTitle": "How to enter expressions",
      "syntaxText": "Operators: + − * / ^ and parentheses. Functions: sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. Constants: pi (π), e, i. Use a decimal point: 3.5. Large number: 2*10^50. Complex number: 3+4*i. Type function names in lowercase Latin letters.",
      "symbolicHelp": "Numeric mode calculates values; symbolic mode returns exact expressions. Variable names start with a Latin letter, followed by letters, digits or _. Function names and pi, e, i are reserved. Expressions with variables stay under the root: √(x²) is not always x. Symbolic trigonometry requires radians.",
      "accuracyHelp": "Precision is 1–100 significant digits, not decimal places; trailing zeros are omitted. Subtracting large, nearly equal numbers can lose precision: check again with higher precision. Numeric mode supports radians and degrees. Inverse trigonometric functions accept real arguments within their domains only. Input is limited to 1000 characters and calculation time to 8 seconds.",
      "footer": "pear · Square root calculator",
      "done": "CALCULATED",
      "busy": "Calculating…",
      "exact": "EXACT EXPRESSION",
      "formal": "FORMULA",
      "copied": "Copied",
      "fontDown": "Decrease font size",
      "fontUp": "Increase font size",
      "generic": "Cannot calculate this expression. Check the syntax and function domains.",
      "input": "Enter an expression with up to 1000 characters.",
      "syntax": "Check parentheses and operators. Example: sin(pi/2) + 3.",
      "division": "Division by zero is not allowed.",
      "domain": "Argument is outside the function domain.",
      "variable": "Replace variables with numbers in numeric mode. For variables, use symbolic mode and Latin names.",
      "precision": "Choose between 1 and 100 significant digits.",
      "function": "Unsupported function. See the input reference.",
      "arguments": "The function must have one argument.",
      "complexity": "Expression is too complex. Split it into smaller parts.",
      "timeout": "Calculation exceeded 8 seconds. Simplify the expression.",
      "range": "Result exceeds the supported range (exponent up to 10,000).",
      "inverse": "Inverse trigonometric functions only accept real arguments here.",
      "symbolicDegrees": "Use radians for trigonometry in symbolic mode.",
      "formalNote": "Formal principal root without simplification. Variables are unspecified; the domain depends on the expression.",
      "exactNote": "Exact symbolic expression. Switch to numeric mode for a decimal value.",
      "valueLabel": "Expression value: ",
      "precisionLabel": "Significant digits: ",
      "zeroNote": "Zero has one root: 0.",
      "failed": "INPUT ERROR",
      "stale": "SETTINGS CHANGED",
      "staleNote": "Press Calculate root to update the result.",
      "copyFailed": "Cannot copy automatically. Select the result manually.",
      "clear": "Clear",
      "support": "Support:",
      "power": "Raise to a power",
      "powerTitle": "Raise to a power",
      "powerDescription": "Enter a number, variable or expression and its exponent.",
      "powerBase": "Base",
      "powerExponent": "Exponent",
      "basePlaceholder": "For example, x or 2 + 3",
      "exponentPlaceholder": "For example, 3 or 1/2",
      "cancel": "Cancel",
      "insertPower": "Insert",
      "powerRequired": "Enter both the base and the exponent.",
      "entryHelp": "Enter only what goes under the square root. Calculate root takes the square root of that expression. Examples: 144 → 12; −49 → 7i; 0 → 0. Enter calculates; Shift+Enter adds a line. Clear removes all input and the result.",
      "powerHelp": "The two-square button inserts any power: fill in the base and exponent. Select text in the input first to use it as the base. Examples: (x)^(3), (2+3)^(4), (16)^(1/2). When typing, use ^ for powers and * for multiplication: 2*x. Choose symbolic mode for variables."
    }
  },
  "zh": {
    "name": "中文",
    "strings": {
      "language": "语言",
      "contrast": "高对比度",
      "title": "平方根计算器",
      "subtitle": "在此计算实数、复数和表达式。",
      "inputTitle": "根号内是什么？",
      "expression": "数字或表达式",
      "hint": "只需输入根号内的表达式。例如：144 或 sin(pi/2) + 3。",
      "mode": "模式",
      "numeric": "数值",
      "symbolic": "符号",
      "angle": "角度单位",
      "radians": "弧度",
      "degrees": "角度",
      "digits": "有效数字",
      "digitHint": "1 到 100",
      "both": "显示 z² = A 的两个根",
      "calculate": "计算平方根 ↗",
      "resultTitle": "结果",
      "ready": "等待计算",
      "principal": "主平方根",
      "second": "另一个平方根",
      "resultHint": "输入表达式，然后点击“计算平方根”。",
      "copy": "复制结果",
      "examples": "试试这些示例",
      "exampleHint": "点击即可计算",
      "exNumber": "简单数字",
      "exComplex": "复数平方根",
      "exTrig": "三角函数",
      "exFormula": "含变量的表达式",
      "syntaxTitle": "如何输入表达式",
      "syntaxText": "运算符：+ − * / ^ 和括号。函数：sqrt、sin、cos、tan (tg)、cot (ctg)、asin、acos、atan、sinh、cosh、tanh、exp、log (ln)、log10、abs。常量：pi (π)、e、i。小数使用英文句点，如 3.5。大数示例：2*10^50。复数示例：3+4*i。函数名必须使用小写拉丁字母。",
      "symbolicHelp": "数值模式计算数值，符号模式返回精确表达式。变量名以拉丁字母开头，后面可包含字母、数字或下划线。函数名和 pi、e、i 为保留名称。含变量的表达式保留在根号内：√(x²) 并不总等于 x。符号模式的三角函数必须使用弧度。",
      "accuracyHelp": "精度为 1–100 位有效数字，并非小数位数；末尾不补零。两个接近的大数相减可能损失精度，请提高精度后复核。数值模式支持弧度和角度。反三角函数只接受其定义域内的实数参数。输入最多 1000 个字符，计算时间上限为 8 秒。",
      "footer": "pear · 平方根计算器",
      "done": "计算完成",
      "busy": "正在计算…",
      "exact": "精确表达式",
      "formal": "公式",
      "copied": "已复制",
      "fontDown": "缩小字体",
      "fontUp": "放大字体",
      "generic": "无法计算此表达式。请检查语法和函数定义域。",
      "input": "请输入不超过 1000 个字符的表达式。",
      "syntax": "请检查括号和运算符。例如：sin(pi/2) + 3。",
      "division": "不能除以零。",
      "domain": "参数超出了函数的定义域。",
      "variable": "数值模式下请将变量替换为数字。使用变量时，请选择符号模式，并使用拉丁字母命名。",
      "precision": "请选择 1 到 100 位有效数字。",
      "function": "不支持此函数。请查看输入帮助。",
      "arguments": "函数必须且只能有一个参数。",
      "complexity": "表达式过于复杂，请拆分计算。",
      "timeout": "计算已超过 8 秒，请简化表达式。",
      "range": "结果超出了支持的范围（指数最多为 10,000）。",
      "inverse": "此处的反三角函数只接受实数参数。",
      "symbolicDegrees": "符号模式下的三角函数请使用弧度。",
      "formalNote": "未化简的形式主平方根。变量值未指定，定义域取决于表达式。",
      "exactNote": "精确的符号表达式。如需小数结果，请切换到数值模式。",
      "valueLabel": "根号内表达式的值：",
      "precisionLabel": "有效数字位数：",
      "zeroNote": "零只有一个平方根：0。",
      "failed": "输入错误",
      "stale": "设置已更改",
      "staleNote": "请点击“计算平方根”以更新结果。",
      "copyFailed": "无法自动复制，请手动选择结果。",
      "clear": "清空",
      "support": "技术支持：",
      "power": "乘方",
      "powerTitle": "乘方",
      "powerDescription": "输入数字、变量或表达式，以及所需的指数。",
      "powerBase": "底数",
      "powerExponent": "指数",
      "basePlaceholder": "例如 x 或 2 + 3",
      "exponentPlaceholder": "例如 3 或 1/2",
      "cancel": "取消",
      "insertPower": "插入",
      "powerRequired": "请填写底数和指数。",
      "entryHelp": "只需输入平方根号内的内容。“计算平方根”会对此表达式开平方。例如：144 → 12；−49 → 7i；0 → 0。Enter 键用于计算，Shift+Enter 用于换行。“清空”会删除全部输入和结果。",
      "powerHelp": "双方框按钮用于插入任意乘方：填写底数和指数即可。也可以先选中输入框中的文字，将其作为底数。示例：(x)^(3)、(2+3)^(4)、(16)^(1/2)。手动输入时，^ 表示乘方，* 表示乘法，如 2*x。含变量时请选择符号模式。"
    }
  },
  "fr": {
    "name": "Français",
    "strings": {
      "language": "Langue",
      "contrast": "Contraste",
      "title": "Calculateur de racines",
      "subtitle": "Nombres, valeurs complexes et expressions au même endroit.",
      "inputTitle": "Que mettre sous la racine ?",
      "expression": "Nombre ou expression",
      "hint": "Saisissez uniquement l’expression sous la racine. Par exemple : 144 ou sin(pi/2) + 3.",
      "mode": "Mode",
      "numeric": "Numérique",
      "symbolic": "Symbolique",
      "angle": "Angles",
      "radians": "Radians",
      "degrees": "Degrés",
      "digits": "Chiffres significatifs",
      "digitHint": "De 1 à 100",
      "both": "Afficher les deux racines de z² = A",
      "calculate": "Calculer la racine ↗",
      "resultTitle": "Résultat",
      "ready": "PRÊT À CALCULER",
      "principal": "Racine carrée principale",
      "second": "Seconde racine",
      "resultHint": "Saisissez une expression et appuyez sur « Calculer la racine ».",
      "copy": "Copier le résultat",
      "examples": "Essayez un exemple",
      "exampleHint": "Cliquez pour calculer",
      "exNumber": "Nombre simple",
      "exComplex": "Racine complexe",
      "exTrig": "Trigonométrie",
      "exFormula": "Expression avec variable",
      "syntaxTitle": "Comment saisir les expressions",
      "syntaxText": "Opérateurs : + − * / ^ et parenthèses. Fonctions : sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. Constantes : pi (π), e, i. Séparateur décimal : un point, comme 3.5. Grand nombre : 2*10^50. Nombre complexe : 3+4*i. Écrivez les fonctions en lettres latines minuscules.",
      "symbolicHelp": "Le mode numérique calcule des valeurs ; le mode symbolique donne des expressions exactes. Une variable commence par une lettre latine, suivie de lettres, chiffres ou _. Les noms de fonctions et pi, e, i sont réservés. Les expressions avec variables restent sous la racine : √(x²) n’est pas toujours x. La trigonométrie symbolique utilise les radians.",
      "accuracyHelp": "La précision va de 1 à 100 chiffres significatifs, et non décimales ; les zéros finaux sont omis. Soustraire de grands nombres proches peut réduire la précision : vérifiez avec une précision supérieure. Le mode numérique accepte radians et degrés. Les fonctions trigonométriques inverses acceptent uniquement des arguments réels dans leur domaine. Limites : 1000 caractères et 8 secondes par calcul.",
      "footer": "pear · Calculateur de racines carrées",
      "done": "CALCUL TERMINÉ",
      "busy": "Calcul en cours…",
      "exact": "EXPRESSION EXACTE",
      "formal": "FORMULE",
      "copied": "Copié",
      "fontDown": "Réduire la taille du texte",
      "fontUp": "Agrandir le texte",
      "generic": "Impossible de calculer cette expression. Vérifiez la syntaxe et le domaine des fonctions.",
      "input": "Saisissez une expression de 1000 caractères maximum.",
      "syntax": "Vérifiez les parenthèses et les opérateurs. Exemple : sin(pi/2) + 3.",
      "division": "La division par zéro est impossible.",
      "domain": "L’argument est en dehors du domaine de la fonction.",
      "variable": "En mode numérique, remplacez les variables par des nombres. Pour les variables, utilisez le mode symbolique et des noms latins.",
      "precision": "Choisissez entre 1 et 100 chiffres significatifs.",
      "function": "Fonction non prise en charge. Consultez l’aide à la saisie.",
      "arguments": "La fonction doit avoir un seul argument.",
      "complexity": "Expression trop complexe. Divisez-la en plusieurs parties.",
      "timeout": "Le calcul a dépassé 8 secondes. Simplifiez l’expression.",
      "range": "Le résultat dépasse la plage autorisée (exposant jusqu’à 10 000).",
      "inverse": "Les fonctions trigonométriques inverses acceptent ici uniquement des arguments réels.",
      "symbolicDegrees": "Utilisez les radians pour la trigonométrie symbolique.",
      "formalNote": "Racine principale formelle, sans simplification. Les variables ne sont pas définies ; le domaine dépend de l’expression.",
      "exactNote": "Expression symbolique exacte. Passez en mode numérique pour une valeur décimale.",
      "valueLabel": "Valeur sous la racine : ",
      "precisionLabel": "Chiffres significatifs : ",
      "zeroNote": "Zéro a une seule racine : 0.",
      "failed": "ERREUR DE SAISIE",
      "stale": "PARAMÈTRES MODIFIÉS",
      "staleNote": "Appuyez sur « Calculer la racine » pour actualiser le résultat.",
      "copyFailed": "Copie automatique impossible. Sélectionnez le résultat manuellement.",
      "clear": "Effacer",
      "support": "Assistance :",
      "power": "Élever à une puissance",
      "powerTitle": "Élever à une puissance",
      "powerDescription": "Saisissez un nombre, une variable ou une expression et son exposant.",
      "powerBase": "Base",
      "powerExponent": "Exposant",
      "basePlaceholder": "Par exemple, x ou 2 + 3",
      "exponentPlaceholder": "Par exemple, 3 ou 1/2",
      "cancel": "Annuler",
      "insertPower": "Insérer",
      "powerRequired": "Renseignez la base et l’exposant.",
      "entryHelp": "Saisissez uniquement l’expression sous la racine carrée. Le bouton « Calculer la racine » en extrait la racine. Exemples : 144 → 12 ; −49 → 7i ; 0 → 0. Entrée calcule ; Maj+Entrée ajoute une ligne. « Effacer » supprime la saisie et le résultat.",
      "powerHelp": "Le bouton à deux carrés insère une puissance : renseignez la base et l’exposant. Sélectionnez d’abord du texte pour l’utiliser comme base. Exemples : (x)^(3), (2+3)^(4), (16)^(1/2). Utilisez ^ pour les puissances et * pour la multiplication : 2*x. Pour les variables, choisissez le mode symbolique."
    }
  },
  "pt": {
    "name": "Português",
    "strings": {
      "language": "Idioma",
      "contrast": "Contraste",
      "title": "Calculadora de raízes",
      "subtitle": "Números, valores complexos e expressões em um só lugar.",
      "inputTitle": "O que vai sob a raiz?",
      "expression": "Número ou expressão",
      "hint": "Digite apenas a expressão sob a raiz. Por exemplo: 144 ou sin(pi/2) + 3.",
      "mode": "Modo",
      "numeric": "Numérico",
      "symbolic": "Simbólico",
      "angle": "Ângulos",
      "radians": "Radianos",
      "degrees": "Graus",
      "digits": "Algarismos significativos",
      "digitHint": "De 1 a 100",
      "both": "Mostrar as duas raízes de z² = A",
      "calculate": "Calcular raiz ↗",
      "resultTitle": "Resultado",
      "ready": "PRONTO PARA CALCULAR",
      "principal": "Raiz quadrada principal",
      "second": "Segunda raiz",
      "resultHint": "Digite uma expressão e pressione «Calcular raiz».",
      "copy": "Copiar resultado",
      "examples": "Experimente um exemplo",
      "exampleHint": "Clique para calcular",
      "exNumber": "Número simples",
      "exComplex": "Raiz complexa",
      "exTrig": "Trigonometria",
      "exFormula": "Expressão com variável",
      "syntaxTitle": "Como inserir expressões",
      "syntaxText": "Operadores: + − * / ^ e parênteses. Funções: sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. Constantes: pi (π), e, i. Use ponto decimal: 3.5. Número grande: 2*10^50. Número complexo: 3+4*i. Escreva as funções em letras latinas minúsculas.",
      "symbolicHelp": "O modo numérico calcula valores; o simbólico retorna expressões exatas. Nomes de variáveis começam com uma letra latina, seguida de letras, números ou _. Nomes de funções e pi, e, i são reservados. Expressões com variáveis permanecem sob a raiz: √(x²) nem sempre é x. A trigonometria simbólica exige radianos.",
      "accuracyHelp": "A precisão é de 1 a 100 algarismos significativos, não casas decimais; zeros finais são omitidos. Subtrair números grandes quase iguais pode reduzir a precisão: confira com precisão maior. O modo numérico aceita radianos e graus. Funções trigonométricas inversas aceitam apenas argumentos reais em seus domínios. Limites: 1000 caracteres e 8 segundos por cálculo.",
      "footer": "pear · Calculadora de raízes quadradas",
      "done": "CALCULADO",
      "busy": "Calculando…",
      "exact": "EXPRESSÃO EXATA",
      "formal": "FÓRMULA",
      "copied": "Copiado",
      "fontDown": "Diminuir o texto",
      "fontUp": "Aumentar o texto",
      "generic": "Não foi possível calcular a expressão. Verifique a sintaxe e o domínio das funções.",
      "input": "Digite uma expressão com até 1000 caracteres.",
      "syntax": "Verifique os parênteses e os operadores. Exemplo: sin(pi/2) + 3.",
      "division": "Não é possível dividir por zero.",
      "domain": "O argumento está fora do domínio da função.",
      "variable": "No modo numérico, substitua variáveis por números. Para variáveis, use o modo simbólico e nomes latinos.",
      "precision": "Escolha de 1 a 100 algarismos significativos.",
      "function": "Função não suportada. Consulte a ajuda de entrada.",
      "arguments": "A função deve ter apenas um argumento.",
      "complexity": "A expressão é muito complexa. Divida-a em partes.",
      "timeout": "O cálculo excedeu 8 segundos. Simplifique a expressão.",
      "range": "O resultado excede o intervalo suportado (expoente até 10 000).",
      "inverse": "As funções trigonométricas inversas aceitam apenas argumentos reais aqui.",
      "symbolicDegrees": "Use radianos para trigonometria no modo simbólico.",
      "formalNote": "Raiz principal formal sem simplificação. As variáveis não foram definidas; o domínio depende da expressão.",
      "exactNote": "Expressão simbólica exata. Mude para o modo numérico para obter um valor decimal.",
      "valueLabel": "Valor sob a raiz: ",
      "precisionLabel": "Algarismos significativos: ",
      "zeroNote": "Zero tem uma única raiz: 0.",
      "failed": "ERRO DE ENTRADA",
      "stale": "CONFIGURAÇÕES ALTERADAS",
      "staleNote": "Pressione «Calcular raiz» para atualizar o resultado.",
      "copyFailed": "Não foi possível copiar automaticamente. Selecione o resultado manualmente.",
      "clear": "Limpar",
      "support": "Suporte:",
      "power": "Elevar a uma potência",
      "powerTitle": "Elevar a uma potência",
      "powerDescription": "Digite um número, uma variável ou uma expressão e seu expoente.",
      "powerBase": "Base",
      "powerExponent": "Expoente",
      "basePlaceholder": "Por exemplo, x ou 2 + 3",
      "exponentPlaceholder": "Por exemplo, 3 ou 1/2",
      "cancel": "Cancelar",
      "insertPower": "Inserir",
      "powerRequired": "Preencha a base e o expoente.",
      "entryHelp": "Digite apenas o que fica sob a raiz quadrada. «Calcular raiz» extrai a raiz dessa expressão. Exemplos: 144 → 12; −49 → 7i; 0 → 0. Enter calcula; Shift+Enter adiciona uma linha. «Limpar» apaga toda a entrada e o resultado.",
      "powerHelp": "O botão com dois quadrados insere uma potência: preencha a base e o expoente. Selecione um texto antes para usá-lo como base. Exemplos: (x)^(3), (2+3)^(4), (16)^(1/2). Use ^ para potências e * para multiplicar: 2*x. Para variáveis, escolha o modo simbólico."
    }
  },
  "es": {
    "name": "Español",
    "strings": {
      "language": "Idioma",
      "contrast": "Contraste",
      "title": "Calculadora de raíces",
      "subtitle": "Números, valores complejos y expresiones en un solo lugar.",
      "inputTitle": "¿Qué va bajo la raíz?",
      "expression": "Número o expresión",
      "hint": "Introduce solo la expresión bajo la raíz. Por ejemplo: 144 o sin(pi/2) + 3.",
      "mode": "Modo",
      "numeric": "Numérico",
      "symbolic": "Simbólico",
      "angle": "Ángulos",
      "radians": "Radianes",
      "degrees": "Grados",
      "digits": "Cifras significativas",
      "digitHint": "De 1 a 100",
      "both": "Mostrar ambas raíces de z² = A",
      "calculate": "Calcular raíz ↗",
      "resultTitle": "Resultado",
      "ready": "LISTO PARA CALCULAR",
      "principal": "Raíz cuadrada principal",
      "second": "Segunda raíz",
      "resultHint": "Introduce una expresión y pulsa «Calcular raíz».",
      "copy": "Copiar resultado",
      "examples": "Prueba un ejemplo",
      "exampleHint": "Pulsa para calcular",
      "exNumber": "Número sencillo",
      "exComplex": "Raíz compleja",
      "exTrig": "Trigonometría",
      "exFormula": "Expresión con variable",
      "syntaxTitle": "Cómo introducir expresiones",
      "syntaxText": "Operadores: + − * / ^ y paréntesis. Funciones: sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. Constantes: pi (π), e, i. Usa un punto decimal: 3.5. Número grande: 2*10^50. Número complejo: 3+4*i. Escribe las funciones en letras latinas minúsculas.",
      "symbolicHelp": "El modo numérico calcula valores; el simbólico devuelve expresiones exactas. Los nombres de variables empiezan con una letra latina y siguen con letras, cifras o _. Los nombres de funciones y pi, e, i están reservados. Las expresiones con variables permanecen bajo la raíz: √(x²) no siempre es x. La trigonometría simbólica requiere radianes.",
      "accuracyHelp": "La precisión va de 1 a 100 cifras significativas, no decimales; se omiten los ceros finales. Restar números grandes casi iguales puede reducir la precisión: comprueba con una precisión mayor. El modo numérico admite radianes y grados. Las funciones trigonométricas inversas solo aceptan argumentos reales dentro de su dominio. Límites: 1000 caracteres y 8 segundos por cálculo.",
      "footer": "pear · Calculadora de raíces cuadradas",
      "done": "CALCULADO",
      "busy": "Calculando…",
      "exact": "EXPRESIÓN EXACTA",
      "formal": "FÓRMULA",
      "copied": "Copiado",
      "fontDown": "Reducir tamaño del texto",
      "fontUp": "Aumentar tamaño del texto",
      "generic": "No se puede calcular la expresión. Revisa la sintaxis y el dominio de las funciones.",
      "input": "Introduce una expresión de hasta 1000 caracteres.",
      "syntax": "Revisa los paréntesis y los operadores. Ejemplo: sin(pi/2) + 3.",
      "division": "No se puede dividir entre cero.",
      "domain": "El argumento está fuera del dominio de la función.",
      "variable": "En modo numérico, sustituye las variables por números. Para variables, usa el modo simbólico y nombres latinos.",
      "precision": "Elige entre 1 y 100 cifras significativas.",
      "function": "Función no admitida. Consulta la ayuda de entrada.",
      "arguments": "La función debe tener un solo argumento.",
      "complexity": "La expresión es demasiado compleja. Divídela en partes.",
      "timeout": "El cálculo ha superado los 8 segundos. Simplifica la expresión.",
      "range": "El resultado supera el intervalo admitido (exponente hasta 10 000).",
      "inverse": "Las funciones trigonométricas inversas solo aceptan argumentos reales aquí.",
      "symbolicDegrees": "Usa radianes para la trigonometría en modo simbólico.",
      "formalNote": "Raíz principal formal sin simplificar. Las variables no están definidas; el dominio depende de la expresión.",
      "exactNote": "Expresión simbólica exacta. Cambia al modo numérico para obtener un valor decimal.",
      "valueLabel": "Valor bajo la raíz: ",
      "precisionLabel": "Cifras significativas: ",
      "zeroNote": "El cero tiene una sola raíz: 0.",
      "failed": "ERROR DE ENTRADA",
      "stale": "AJUSTES MODIFICADOS",
      "staleNote": "Pulsa «Calcular raíz» para actualizar el resultado.",
      "copyFailed": "No se pudo copiar automáticamente. Selecciona el resultado manualmente.",
      "clear": "Borrar",
      "support": "Soporte:",
      "power": "Elevar a una potencia",
      "powerTitle": "Elevar a una potencia",
      "powerDescription": "Introduce un número, una variable o una expresión y su exponente.",
      "powerBase": "Base",
      "powerExponent": "Exponente",
      "basePlaceholder": "Por ejemplo, x o 2 + 3",
      "exponentPlaceholder": "Por ejemplo, 3 o 1/2",
      "cancel": "Cancelar",
      "insertPower": "Insertar",
      "powerRequired": "Introduce la base y el exponente.",
      "entryHelp": "Introduce solo lo que va bajo la raíz cuadrada. «Calcular raíz» extrae la raíz de esa expresión. Ejemplos: 144 → 12; −49 → 7i; 0 → 0. Intro calcula; Mayús+Intro añade una línea. «Borrar» elimina toda la entrada y el resultado.",
      "powerHelp": "El botón de dos cuadrados inserta una potencia: completa la base y el exponente. Puedes seleccionar texto para usarlo como base. Ejemplos: (x)^(3), (2+3)^(4), (16)^(1/2). Usa ^ para potencias y * para multiplicar: 2*x. Para variables, elige el modo simbólico."
    }
  },
  "ar": {
    "name": "العربية",
    "strings": {
      "language": "اللغة",
      "contrast": "التباين",
      "title": "حاسبة الجذور",
      "subtitle": "الأعداد والقيم المركبة والتعبيرات في مكان واحد.",
      "inputTitle": "ما الذي تحت الجذر؟",
      "expression": "عدد أو تعبير",
      "hint": "أدخل التعبير الموجود تحت الجذر فقط. مثال: 144 أو sin(pi/2) + 3.",
      "mode": "الوضع",
      "numeric": "عددي",
      "symbolic": "رمزي",
      "angle": "وحدة الزاوية",
      "radians": "راديان",
      "degrees": "درجات",
      "digits": "الأرقام المعنوية",
      "digitHint": "من 1 إلى 100",
      "both": "إظهار جذري المعادلة z² = A",
      "calculate": "حساب الجذر ↗",
      "resultTitle": "النتيجة",
      "ready": "جاهز للحساب",
      "principal": "الجذر التربيعي الرئيسي",
      "second": "الجذر الآخر",
      "resultHint": "أدخل تعبيرًا ثم اضغط على «حساب الجذر».",
      "copy": "نسخ النتيجة",
      "examples": "جرّب مثالًا",
      "exampleHint": "اضغط للحساب",
      "exNumber": "عدد بسيط",
      "exComplex": "جذر مركب",
      "exTrig": "حساب المثلثات",
      "exFormula": "تعبير يحتوي على متغير",
      "syntaxTitle": "كيفية إدخال التعبيرات",
      "syntaxText": "العمليات: + − * / ^ والأقواس. الدوال: sqrt, sin, cos, tan (tg), cot (ctg), asin, acos, atan, sinh, cosh, tanh, exp, log (ln), log10, abs. الثوابت: pi (π), e, i. استخدم الأرقام 0–9 والنقطة للفاصل العشري، مثل 3.5. عدد كبير: 2*10^50. عدد مركب: 3+4*i. اكتب أسماء الدوال بحروف لاتينية صغيرة.",
      "symbolicHelp": "الوضع العددي يحسب القيم، والوضع الرمزي يعيد تعبيرات دقيقة. يبدأ اسم المتغير بحرف لاتيني تتبعه حروف أو أرقام أو _. أسماء الدوال والثوابت pi وe وi محجوزة. تبقى التعبيرات ذات المتغيرات تحت الجذر: √(x²) لا يساوي دائمًا x. حساب المثلثات الرمزي يتطلب الراديان.",
      "accuracyHelp": "الدقة من 1 إلى 100 رقم معنوي، وليست عدد المنازل العشرية؛ لا تُضاف أصفار نهائية. قد يؤدي طرح عددين كبيرين متقاربين إلى فقدان الدقة؛ أعد التحقق بدقة أعلى. يدعم الوضع العددي الراديان والدرجات. تقبل الدوال المثلثية العكسية قيمًا حقيقية ضمن مجالها فقط. الحد الأقصى 1000 محرف و8 ثوانٍ للحساب.",
      "footer": "pear · حاسبة الجذور التربيعية",
      "done": "اكتمل الحساب",
      "busy": "جارٍ الحساب…",
      "exact": "تعبير دقيق",
      "formal": "صيغة",
      "copied": "تم النسخ",
      "fontDown": "تصغير النص",
      "fontUp": "تكبير النص",
      "generic": "تعذر حساب التعبير. تحقق من الصياغة ومجال الدوال.",
      "input": "أدخل تعبيرًا لا يتجاوز 1000 محرف.",
      "syntax": "تحقق من الأقواس وعلامات العمليات. مثال: sin(pi/2) + 3.",
      "division": "لا يمكن القسمة على صفر.",
      "domain": "القيمة خارج مجال الدالة.",
      "variable": "استبدل المتغيرات بأعداد في الوضع العددي. لاستخدام المتغيرات اختر الوضع الرمزي وأسماء لاتينية.",
      "precision": "اختر من 1 إلى 100 رقم معنوي.",
      "function": "هذه الدالة غير مدعومة. راجع تعليمات الإدخال.",
      "arguments": "يجب أن تحتوي الدالة على وسيط واحد فقط.",
      "complexity": "التعبير معقد جدًا. قسّمه إلى أجزاء.",
      "timeout": "تجاوز الحساب 8 ثوانٍ. بسّط التعبير.",
      "range": "تتجاوز النتيجة النطاق المدعوم (الأس حتى 10,000).",
      "inverse": "تقبل الدوال المثلثية العكسية هنا قيمًا حقيقية فقط.",
      "symbolicDegrees": "استخدم الراديان لحساب المثلثات في الوضع الرمزي.",
      "formalNote": "الجذر الرئيسي بصيغته دون تبسيط. قيم المتغيرات غير محددة، والمجال يعتمد على التعبير.",
      "exactNote": "تعبير رمزي دقيق. انتقل إلى الوضع العددي للحصول على قيمة عشرية.",
      "valueLabel": "قيمة التعبير تحت الجذر: ",
      "precisionLabel": "الأرقام المعنوية: ",
      "zeroNote": "للصفر جذر واحد: 0.",
      "failed": "خطأ في الإدخال",
      "stale": "تغيّرت الإعدادات",
      "staleNote": "اضغط على «حساب الجذر» لتحديث النتيجة.",
      "copyFailed": "تعذر النسخ تلقائيًا. حدد النتيجة يدويًا.",
      "clear": "مسح",
      "support": "الدعم الفني:",
      "power": "رفع إلى قوة",
      "powerTitle": "رفع إلى قوة",
      "powerDescription": "أدخل عددًا أو متغيرًا أو تعبيرًا، ثم الأس المطلوب.",
      "powerBase": "الأساس",
      "powerExponent": "الأس",
      "basePlaceholder": "مثل x أو 2 + 3",
      "exponentPlaceholder": "مثل 3 أو 1/2",
      "cancel": "إلغاء",
      "insertPower": "إدراج",
      "powerRequired": "أدخل الأساس والأس معًا.",
      "entryHelp": "أدخل ما يقع تحت الجذر التربيعي فقط. يستخرج زر «حساب الجذر» جذر هذا التعبير. أمثلة: 144 → 12؛ −49 → 7i؛ 0 → 0. يحسب مفتاح Enter النتيجة، ويضيف Shift+Enter سطرًا جديدًا. يحذف «مسح» جميع المدخلات والنتيجة.",
      "powerHelp": "يُدرج الزر ذو المربعين قوة من اختيارك: أدخل الأساس والأس. يمكنك تحديد نص أولًا لاستخدامه كأساس. أمثلة: (x)^(3)، (2+3)^(4)، (16)^(1/2). استخدم ^ للقوى و* للضرب: 2*x. اختر الوضع الرمزي للمتغيرات."
    }
  }
};
